### ISSUE TITLE
TODO: make sure that `map.removeLayer(shades)` works

### ISSUE THREAD

**Issue by mkong0216** [mkong0216/leaflet-shades#4]
Reference: issue #3 

According to the reference issue even when `map.removeLayer(shades)` is called the `shades` are still active with event listeners. Check why this is happening and figure out a fix.

**Comment by h0lg** [comment]
I'm experiencing the same issue. The `moveend` handler of the `map` keeps firing after the `shades` layer has been removed.
This is happening because the code for the unbinding of the map event handlers reads like this:

`map.off('moveend', this._updatedMapPosition.bind(this));`

According to [these docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) **bind() creates a new function**, i.e. a function that is equal in functionality but _not equal in reference_ to the handle you bound using the same expression in `_addEventListeners` via

`this._map.on('moveend', this._updatedMapPosition.bind(this));`

So the unbinding code is trying to unbind a newly created handler that was never bound instead of the old one that was.

If you bind and remember the reference to the handler like this

```JS
this._handleMapMoved = this._updatedMapPosition.bind(this);
this._map.on('moveend', this._handleMapMoved);
```

and unbind the same handler via its reference like this

`map.off('moveend', this._handleMapMoved);`

the handlers get unbound successfully.

**Comment by h0lg** [comment]
Have a look at above PR, it should fix the issue. Without it, this workaround cleans up the map instance after removing the shades (leaflet 1.7.1):

```JS 
                        var unbindMapEvent = function (type, funcName) {
                            var handlers = map._events[type].filter(function (handler) {
                                return handler.fn.name === "bound " + funcName;
                            });

                            handlers.forEach(function (handler) { map.off(type, handler.fn); });
                        };

                        unbindMapEvent("editable:drawing:commit", "_onBoundsChanged");
                        unbindMapEvent("editable:vertex:dragend", "_onBoundsChanged");
                        unbindMapEvent("editable:dragend", "_onBoundsChanged");
                        unbindMapEvent("moveend", "_updatedMapPosition");
```
